Google maps area
trew/PokemonGoMapNotifier pull request #1
Opened 2016-12-23 20:59 UTC by krilun

Added Google Maps preview, area-name and reformatted

2016-12-23 22:18 UTC, trew requested changes

2016-12-23 22:18 UTC, trew commented on server.py
> +from Queue import Queue
Det här vill jag bekräfta på min burk först ...

2016-12-23 22:18 UTC, trew commented on server.py
> +    maps = "Google Maps: {}{}".format(maps, " in " + sublocality if sublocality != "" else "") if maps else ""
Det här tror jag blir fel om sublocality inte finns. Jag skulle nog på en ny rad istället lagt till typ:

```python
if sublocality:
    maps += " in " + sublocality
```

2016-12-24 09:10 UTC, krilun commented on server.py
> +    maps = "Google Maps: {}{}".format(maps, " in " + sublocality if sublocality != "" else "") if maps else ""
Testade med koordinater som inte gav träff och funkar. Typ vid valla

2016-12-24 09:33 UTC, merged